In [1]:
import netCDF4 as nc
from netCDF4 import Dataset
import json

In [10]:
# database {table+}
# table {column+, product+}
# column (long_name, unit, datatype)

database={
    "merra2_2d_monthly" : {
        "products" : {},
        "variables" : {}
    },
    "merra2_l72_3hr" : {
        "products" : {},
        "variables" : {}        
    },
    "merra_2d" : {
        "products" : {},
        "variables" : {}        
    }
}

# Get Monthly variables

f_list=['MERRA2_400.instM_2d_gas_Nx.202102.nc4',
        'MERRA2_400.tavgM_2d_aer_Nx.202102.nc4',
        'MERRA2_400.tavgM_2d_flx_Nx.202102.nc4',
        'MERRA2_400.tavgM_2d_ocn_Nx.202102.nc4',
        'MERRA2_400.tavgM_2d_slv_Nx.202102.nc4',
        'MERRA2_400.tavgM_2d_adg_Nx.202102.nc4',
        'MERRA2_400.tavgM_2d_chm_Nx.202102.nc4',
        'MERRA2_400.tavgM_2d_lnd_Nx.202102.nc4',
        'MERRA2_400.tavgM_2d_rad_Nx.202102.nc4'
       ]

for f in f_list:
    print (f)
    ds = Dataset(f)
    for v in sorted(ds.variables):
        database['merra2_2d_monthly']['variables'][v] = {
            'long_name' : ds[v].long_name,
            'units'     : ds[v].units,
            'datatype'  : str(ds[v].dtype)
        }
    database['merra2_2d_monthly']['products'][ds.ShortName] = ds.LongName

    ds.close()

f_list=['/home/ec2-user/MERRA2_400.inst1_2d_lfo_Nx.20211004.nc4',
   '/home/ec2-user/MERRA2_400.tavg1_2d_int_Nx.20211004.nc4',
   '/home/ec2-user/MERRA2_400.tavg1_2d_rad_Nx.20211004.nc4',
   '/home/ec2-user/MERRA2_400.tavg1_2d_adg_Nx.20211004.nc4',
   '/home/ec2-user/MERRA2_400.tavg1_2d_lfo_Nx.20211004.nc4',
   '/home/ec2-user/MERRA2_400.tavg1_2d_slv_Nx.20211004.nc4',
   '/home/ec2-user/MERRA2_400.tavg1_2d_aer_Nx.20211004.nc4',
   '/home/ec2-user/MERRA2_400.tavg1_2d_lnd_Nx.20211004.nc4',
   '/home/ec2-user/MERRA2_400.tavg1_2d_flx_Nx.20211004.nc4',
   '/home/ec2-user/MERRA2_400.tavg1_2d_ocn_Nx.20211004.nc4'
  ]

for f in f_list:
    print (f)
    ds = Dataset(f)
    for v in sorted(ds.variables):
        database['merra_2d']['variables'][v] = {
            'long_name' : ds[v].long_name,
            'units'     : ds[v].units,
            'datatype'  : str(ds[v].dtype)
        }
    database['merra_2d']['products']= {ds.ShortName : ds.LongName}
    ds.close()

ds = Dataset('/home/ec2-user/MERRA2_401.inst3_3d_asm_Nv.20210801.nc4')

for v in sorted(ds.variables):
    database['merra2_l72_3hr']['variables'][v] = {
        'long_name' : ds[v].long_name,
        'units'     : ds[v].units,
        'datatype'  : str(ds[v].dtype)
    }
    #print (v, ds[v].long_name, ds[v].units, ds[v].dtype)

database['merra2_l72_3hr']['products']= {ds.ShortName : ds.LongName}

ds.close()

print (json.dumps(database, indent=1))
with open('merra2_database.json', 'w') as f:
    json.dump(database, f)

MERRA2_400.instM_2d_gas_Nx.202102.nc4
MERRA2_400.tavgM_2d_aer_Nx.202102.nc4
MERRA2_400.tavgM_2d_flx_Nx.202102.nc4
MERRA2_400.tavgM_2d_ocn_Nx.202102.nc4
MERRA2_400.tavgM_2d_slv_Nx.202102.nc4
MERRA2_400.tavgM_2d_adg_Nx.202102.nc4
MERRA2_400.tavgM_2d_chm_Nx.202102.nc4
MERRA2_400.tavgM_2d_lnd_Nx.202102.nc4
MERRA2_400.tavgM_2d_rad_Nx.202102.nc4
/home/ec2-user/MERRA2_400.inst1_2d_lfo_Nx.20211004.nc4
/home/ec2-user/MERRA2_400.tavg1_2d_int_Nx.20211004.nc4
/home/ec2-user/MERRA2_400.tavg1_2d_rad_Nx.20211004.nc4
/home/ec2-user/MERRA2_400.tavg1_2d_adg_Nx.20211004.nc4
/home/ec2-user/MERRA2_400.tavg1_2d_lfo_Nx.20211004.nc4
/home/ec2-user/MERRA2_400.tavg1_2d_slv_Nx.20211004.nc4
/home/ec2-user/MERRA2_400.tavg1_2d_aer_Nx.20211004.nc4
/home/ec2-user/MERRA2_400.tavg1_2d_lnd_Nx.20211004.nc4
/home/ec2-user/MERRA2_400.tavg1_2d_flx_Nx.20211004.nc4
/home/ec2-user/MERRA2_400.tavg1_2d_ocn_Nx.20211004.nc4
{
 "merra2_2d_monthly": {
  "products": {
   "M2IMNXGAS": "MERRA2 inst3_2d_gas_Nx: 2d,3-Hourly,Instantaneous

In [4]:
iinputs={}
f = open("merra2_monthly_1980_2000_urls.txt", "r")
x=f.read()
f.close()

urls=x.split('\n')
for u in urls:
    if len(u) == 0:
        continue
    #print (u)
    fileName=(u[u.rindex('/')+1:])
    fparts = fileName.split('.')
    #print (fparts)
    sortkey = fparts[2]
    dskey   = fparts[1]
    if sortkey in inputs:
        inputs[sortkey][dskey]['url']=u
        inputs[sortkey][dskey]['fn']=fileName
    else:
        inputs[sortkey]= {
    "tavgM_2d_adg_Nx" : { "url" : "", "fn" : ""},
    "tavgM_2d_aer_Nx" : { "url" : "", "fn" : ""},
    "tavgM_2d_chm_Nx" : { "url" : "", "fn" : ""},
    "tavgM_2d_flx_Nx" : { "url" : "", "fn" : ""},
    "instM_2d_gas_Nx" : { "url" : "", "fn" : ""},
    "tavgM_2d_lnd_Nx" : { "url" : "", "fn" : ""},
    "tavgM_2d_ocn_Nx" : { "url" : "", "fn" : ""},
    "tavgM_2d_rad_Nx" : { "url" : "", "fn" : ""},
    "tavgM_2d_slv_Nx" : { "url" : "", "fn" : ""}
  }
        inputs[sortkey][dskey]['url']=u
        inputs[sortkey][dskey]['fn']=fileName
        


In [5]:
def do_it(m_str, m):
    #print (m['tavgM_2d_adg_Nx'])
    vars={}
    for d in m:
        ds=m[d]['ds']
        for v in ds.variables:
            if v in vars:
                print ('duplicate variable: ', v, ' skipping ....')
            else:
                ds.set_auto_mask(False)
                if '_FillValue' in ds[v].ncattrs():
                    tmp=ds[v][:]
                    tmp[tmp == ds[v]._FillValue] = np.nan
                    vars[v]=tmp[:]
                else:
                    vars[v]=ds[v][:]
        print (d)
        
# Normalize lat/lon
    vm_lon, vm_lat = np.meshgrid(vars['lon'], vars['lat'])
    print (vm_lat.shape, vm_lon)

# Normalize time

    v_time = nc.num2date(vars['time'][:],ds['time'].units, only_use_python_datetimes=True)
    print (v_time)
    vm_time=np.zeros(207936, dtype='datetime64[s]')
    vm_time[:]= v_time

    print (vm_time[0])

# string for filename
    s_time=[]
    for t in v_time:
        s_time.append(t.strftime("%Y-%m-%d %H:%M:%S").replace( ' ', 'T'))
    print (s_time)


    t_size=vars['time'].size
    for t in range(t_size):
        #print (t)
        stack_this = []
        ctr=0
        for v in sorted(vars):
            #print (ctr, v, vars[v].shape)
            ctr+=1
            if v == 'time':
                vm_time[:] = vm_time
                print ('vmtime', vm_time.shape)
                stack_this.append(vm_time.astype('float'))
            elif v == 'lon':
                stack_this.append(vm_lon.flatten()[:])
            elif v == 'lat':
                stack_this.append(vm_lat.flatten()[:])
            else:
                stack_this.append(vars[v][t].flatten()[:])
        #print (stack_this)
        x=np.dstack( (stack_this) )
        fname = '/home/ec2-user/merra2-2d_monthly_' + m_str + '.tsv.gz'
        np.savetxt(fname, x[0], fmt='%.12f', delimiter='~', newline="\n")        
        
    return



In [ ]:
for m in inputs:
    print (m)
    for d in inputs[m]:
        #print (m, d)
        print (inputs[m][d]['url'], inputs[m][d]['fn'])
        subprocess.run(["curl", "-n", "-c", ".urs_cookies", "-b", ".urs_cookies", "-LJO", "--url", inputs[m][d]['url']])
        inputs[m][d]['ds']=Dataset(inputs[m][d]['fn'])
    do_it(m, inputs[m]) # Create monthly tsv.gz files
    
    for d in inputs[m]:
        inputs[m][d]['ds'].close()
        os.remove(inputs[m][d]['fn'])
        
    stagingS3  = 's3://nasa-ems-sandbox/staging/science/merra-2/2d_1hr/'
    for f in outs:
        rc=subprocess.run(["aws", "s3", "cp", f, stagingS3 ])
#    print ('rc:', rc)
    # Execute insert into ...
    cursor.execute(q)
    print(cursor.description)
    print(cursor.fetchall())
    
    for f in outs:
        
    # Delete s3 staging files
        rc=subprocess.run(["aws", "s3", "rm", stagingS3 + f.rsplit('/', 1)[-1]])
        print ('rc:',rc)
     
    # Delete tsv.gz file(s)
        os.remove(f)

    


198001
https://goldsmr4.gesdisc.eosdis.nasa.gov/data/MERRA2_MONTHLY/M2TMNXADG.5.12.4/1980/MERRA2_100.tavgM_2d_adg_Nx.198001.nc4 MERRA2_100.tavgM_2d_adg_Nx.198001.nc4
https://goldsmr4.gesdisc.eosdis.nasa.gov/data/MERRA2_MONTHLY/M2TMNXAER.5.12.4/1980/MERRA2_100.tavgM_2d_aer_Nx.198001.nc4 MERRA2_100.tavgM_2d_aer_Nx.198001.nc4
https://goldsmr4.gesdisc.eosdis.nasa.gov/data/MERRA2_MONTHLY/M2TMNXCHM.5.12.4/1980/MERRA2_100.tavgM_2d_chm_Nx.198001.nc4 MERRA2_100.tavgM_2d_chm_Nx.198001.nc4
https://goldsmr4.gesdisc.eosdis.nasa.gov/data/MERRA2_MONTHLY/M2TMNXFLX.5.12.4/1980/MERRA2_100.tavgM_2d_flx_Nx.198001.nc4 MERRA2_100.tavgM_2d_flx_Nx.198001.nc4
https://goldsmr4.gesdisc.eosdis.nasa.gov/data/MERRA2_MONTHLY/M2IMNXGAS.5.12.4/1980/MERRA2_100.instM_2d_gas_Nx.198001.nc4 MERRA2_100.instM_2d_gas_Nx.198001.nc4
https://goldsmr4.gesdisc.eosdis.nasa.gov/data/MERRA2_MONTHLY/M2TMNXLND.5.12.4/1980/MERRA2_100.tavgM_2d_lnd_Nx.198001.nc4 MERRA2_100.tavgM_2d_lnd_Nx.198001.nc4
https://goldsmr4.gesdisc.eosdis.nasa.go

In [3]:
ds1=Dataset("MERRA2_400.tavgM_2d_aer_Nx.202112.nc4", "r")
ds2=Dataset("MERRA2_400.tavgM_2d_flx_Nx.202112.nc4", "r")
ds3=Dataset("MERRA2_400.tavgM_2d_slv_Nx.202112.nc4", "r")
ds4=Dataset("MERRA2_400.tavgM_2d_lnd_Nx.202112.nc4", "r")
ds5=Dataset("MERRA2_400.tavgM_2d_adg_Nx.202112.nc4", "r")
ds6=Dataset("MERRA2_400.tavgM_2d_rad_Nx.202112.nc4", "r")
ds7=Dataset("MERRA2_400.tavgM_2d_chm_Nx.202112.nc4", "r")
ds8=Dataset("MERRA2_400.tavgM_2d_ocn_Nx.202112.nc4", "r")
ds9=Dataset("MERRA2_400.instM_2d_gas_Nx.202112.nc4", "r")

In [21]:
ds4['BASEFLOW'].set_auto_mask(False)
#print (ds4['BASEFLOW']._FillValue)
a=ds4['BASEFLOW'][:]
a[a == ds4['BASEFLOW']._FillValue] = np.nan
#print (a[0][-34])
#print (ds4['BASEFLOW'], ds4['BASEFLOW'][0][35])
#np.savetxt('test.tsv', a.flatten(), delimiter='~', newline="\n")
ctr=0
for v in sorted(vars):
    if ctr == 87:
        print (v)
    ctr+=1
#print (ds2)
print(ds4['ECHANGE'])

ECHANGE
<class 'netCDF4._netCDF4.Variable'>
float32 ECHANGE(time, lat, lon)
    long_name: rate_of_change_of_total_land_energy
    units: W m-2
    _FillValue: 1000000000000000.0
    missing_value: 1000000000000000.0
    fmissing_value: 1000000000000000.0
    vmax: 1000000000000000.0
    vmin: -1000000000000000.0
    valid_range: [-1.e+15  1.e+15]
unlimited dimensions: time
current shape = (1, 361, 576)
filling on


In [24]:
#ds4['BASEFLOW'].set_auto_mask(False)
print (ds4['BASEFLOW'].ncattrs())
#a=ds4['BASEFLOW'][:]
#a[a == ds4['BASEFLOW']._FillValue] = np.nan
#print (a[0][-34])
#print (ds4['BASEFLOW'], ds4['BASEFLOW'][0][35])
#np.savetxt('test.tsv', a.flatten(), delimiter='~', newline="\n")


vars={}
for v in ds1.variables:
    ds1[v].set_auto_mask(False)
    if '_FillValue' in ds1[v].ncattrs():
        tmp=ds1[v][:]
        tmp[tmp == ds1[v]._FillValue] = np.nan
        vars[v]=tmp[:]
    else:
        vars[v]=ds1[v][:]

for v in ds2.variables:
    if v in vars:
        print ('duplicate variable: ', v, ' skipping ....')
    else:
        ds2[v].set_auto_mask(False)
        if '_FillValue' in ds2[v].ncattrs():
            tmp=ds2[v][:]
            tmp[tmp == ds2[v]._FillValue] = np.nan
            vars[v]=tmp[:]
        else:
            vars[v]=ds2[v][:]

for v in ds3.variables:
    if v in vars:
        print ('duplicate variable: ', v, ' skipping ....')
    else:
        ds3[v].set_auto_mask(False)
        if '_FillValue' in ds3[v].ncattrs():
            tmp=ds3[v][:]
            tmp[tmp == ds3[v]._FillValue] = np.nan
            vars[v]=tmp[:]
        else:
            vars[v]=ds3[v][:]
        
for v in ds4.variables:
    if v in vars:
        print ('duplicate variable: ', v, ' skipping ....')
    else:
        ds4[v].set_auto_mask(False)
        if '_FillValue' in ds4[v].ncattrs():
            tmp=ds4[v][:]
            tmp[tmp == ds4[v]._FillValue] = np.nan
            vars[v]=tmp[:]
        else:
            vars[v]=ds4[v][:]
    if v == 'ECHANGE':
        print (vars[v])

for v in ds5.variables:
    if v in vars:
        print ('duplicate variable: ', v, ' skipping ....')
    else:
        ds5[v].set_auto_mask(False)
        if '_FillValue' in ds5[v].ncattrs():
            tmp=ds5[v][:]
            tmp[tmp == ds5[v]._FillValue] = np.nan
            vars[v]=tmp[:]
        else:
            vars[v]=ds5[v][:]

for v in ds6.variables:
    if v in vars:
        print ('duplicate variable: ', v, ' skipping ....')
    else:
        ds6[v].set_auto_mask(False)
        if '_FillValue' in ds6[v].ncattrs():
            tmp=ds6[v][:]
            tmp[tmp == ds6[v]._FillValue] = np.nan
            vars[v]=tmp[:]
        else:
            vars[v]=ds6[v][:]

for v in ds7.variables:
    if v in vars:
        print ('duplicate variable: ', v, ' skipping ....')
    else:
        ds7[v].set_auto_mask(False)
        if '_FillValue' in ds7[v].ncattrs():
            tmp=ds7[v][:]
            tmp[tmp == ds7[v]._FillValue] = np.nan
            vars[v]=tmp[:]
        else:
            vars[v]=ds7[v][:]

for v in ds8.variables:
    if v in vars:
        print ('duplicate variable: ', v, ' skipping ....')
    else:
        ds8[v].set_auto_mask(False)
        if '_FillValue' in ds8[v].ncattrs():
            tmp=ds8[v][:]
            tmp[tmp == ds8[v]._FillValue] = np.nan
            vars[v]=tmp[:]
        else:
            vars[v]=ds8[v][:]

for v in ds9.variables:
    if v in vars:
        print ('duplicate variable: ', v, ' skipping ....')
    else:
        ds9[v].set_auto_mask(False)
        if '_FillValue' in ds9[v].ncattrs():
            tmp=ds9[v][:]
            tmp[tmp == ds9[v]._FillValue] = np.nan
            vars[v]=tmp[:]
        else:
            vars[v]=ds9[v][:]


['long_name', 'units', '_FillValue', 'missing_value', 'fmissing_value', 'vmax', 'vmin', 'valid_range']
duplicate variable:  lon  skipping ....
duplicate variable:  lat  skipping ....
duplicate variable:  time  skipping ....
duplicate variable:  lon  skipping ....
duplicate variable:  lat  skipping ....
duplicate variable:  time  skipping ....
duplicate variable:  DISPH  skipping ....
duplicate variable:  Var_DISPH  skipping ....
duplicate variable:  lon  skipping ....
duplicate variable:  lat  skipping ....
duplicate variable:  time  skipping ....
[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  ...
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]]
duplicate variable:  lon  skipping ....
duplicate variable:  lat  skipping ....
duplicate variable:  time  skipping ....
duplicate variable:  lon  skipping ....
duplicate variable:  lat  skipping ....
duplicate variable:  time  skipping ....
dupl

In [25]:

# Normalize lat/lon
vm_lon, vm_lat = np.meshgrid(vars['lon'], vars['lat'])
print (vm_lat.shape, vm_lon)

# Normalize time

v_time = nc.num2date(vars['time'][:],ds2['time'].units, only_use_python_datetimes=True)
print (v_time)
vm_time=np.zeros(207936, dtype='datetime64[s]')
vm_time[:]= v_time

print (vm_time[0])

# string for filename
s_time=[]
for t in v_time:
    s_time.append(t.strftime("%Y-%m-%d %H:%M:%S").replace( ' ', 'T'))
print (s_time)


t_size=vars['time'].size
for t in range(t_size):
    #print (t)
    stack_this = []
    ctr=0
    for v in sorted(vars):
        #print (ctr, v, vars[v].shape)
        ctr+=1
        if v == 'time':
            vm_time[:] = vm_time
            print ('vmtime', vm_time.shape)
            stack_this.append(vm_time.astype('float'))
        elif v == 'lon':
            stack_this.append(vm_lon.flatten()[:])
        elif v == 'lat':
            stack_this.append(vm_lat.flatten()[:])
        else:
            stack_this.append(vars[v][t].flatten()[:])
    #print (stack_this)
    x=np.dstack( (stack_this) )
    fname = '/home/ec2-user/merra2-2d_monthly' + s_time[t].replace(':', '_') + '.tsv.gz'
    np.savetxt(fname, x[0], fmt='%.12f', delimiter='~', newline="\n")
#    np.savetxt(fname, x[0], fmt='%.5f', delimiter='~', newline="\n")
    print (x.shape)
    

(361, 576) [[-180.    -179.375 -178.75  ...  178.125  178.75   179.375]
 [-180.    -179.375 -178.75  ...  178.125  178.75   179.375]
 [-180.    -179.375 -178.75  ...  178.125  178.75   179.375]
 ...
 [-180.    -179.375 -178.75  ...  178.125  178.75   179.375]
 [-180.    -179.375 -178.75  ...  178.125  178.75   179.375]
 [-180.    -179.375 -178.75  ...  178.125  178.75   179.375]]
[cftime.DatetimeGregorian(2021, 12, 1, 0, 30, 0, 0)]
2021-12-01T00:30:00
['2021-12-01T00:30:00']
vmtime (207936,)
(1, 207936, 735)


In [7]:
f = open("merra2-2d-monthly_create_table.sql", "a")
f.write('CREATE EXTERNAL TABLE merra_2d_month (\n')

# Need to manually remove the comma on the last column name.

for v in sorted(vars):
    f.write(v + ' string,\n')

f.write(""" )
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
WITH SERDEPROPERTIES ( 
  'quoteChar'='\u0000', 
  'separatorChar'='~') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://nasa-ems-sandbox/staging/science/merra-2/2d_month'
""")

f.close()

    

In [27]:
sql = 'select\n' 
for v in sorted(vars):
    sql += 'try_cast(' + v + '  as real) ' + v + ',\n'
sql += 'from sci_staging\n'
print (sql)

select
try_cast(ALBEDO  as real) ALBEDO,
try_cast(ALBNIRDF  as real) ALBNIRDF,
try_cast(ALBNIRDR  as real) ALBNIRDR,
try_cast(ALBVISDF  as real) ALBVISDF,
try_cast(ALBVISDR  as real) ALBVISDR,
try_cast(AODANA  as real) AODANA,
try_cast(AODINC  as real) AODINC,
try_cast(BASEFLOW  as real) BASEFLOW,
try_cast(BCANGSTR  as real) BCANGSTR,
try_cast(BCCMASS  as real) BCCMASS,
try_cast(BCDP001  as real) BCDP001,
try_cast(BCDP002  as real) BCDP002,
try_cast(BCEM001  as real) BCEM001,
try_cast(BCEM002  as real) BCEM002,
try_cast(BCEMAN  as real) BCEMAN,
try_cast(BCEMBB  as real) BCEMBB,
try_cast(BCEMBF  as real) BCEMBF,
try_cast(BCEXTTAU  as real) BCEXTTAU,
try_cast(BCFLUXU  as real) BCFLUXU,
try_cast(BCFLUXV  as real) BCFLUXV,
try_cast(BCHYPHIL  as real) BCHYPHIL,
try_cast(BCSCATAU  as real) BCSCATAU,
try_cast(BCSD001  as real) BCSD001,
try_cast(BCSD002  as real) BCSD002,
try_cast(BCSMASS  as real) BCSMASS,
try_cast(BCSV001  as real) BCSV001,
try_cast(BCSV002  as real) BCSV002,
try_cast(BCWT00

In [5]:
v_time = nc.num2date(ds2['time'][:],ds2['time'].units, only_use_python_datetimes=True)
v_lev  = ds2['lev'][:]
v_lon  = ds2['lon'][:]
v_lat  = ds2['lat'][:]
v_CLOUD = np.around(ds2['CLOUD'][:],7)
v_DELP = np.around(ds2['DELP'][:],7 )
v_EPV = np.around(ds2['EPV'][:], 7)
v_H = np.around(ds2['H'][:], 7)
v_O3 = np.around(ds2['O3'][:], 7)
v_OMEGA = np.around(ds2['OMEGA'][:], 7)
v_PHIS = np.around(ds2['PHIS'][:], 7)
v_PL = np.around(ds2['PL'][:], 7)
v_PS = ds2['PS'][:]
v_QI = ds2['QI'][:]
v_QL = ds2['QL'][:]
v_QV = ds2['QV'][:]
v_RH = ds2['RH'][:]
v_SLP = np.around(ds2['SLP'][:],7)
v_T = ds2['T'][:]
v_U = ds2['U'][:]
v_V = ds2['V'][:]

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: WARNING: valid_range not used since it
cannot be safely cast to variable data type
  if __name__ == '__main__':


In [6]:
import datetime
print (v_time)
#print (v_time[0].replace())
#x=v_time[0].strftime("%Y-%m-%d %H:%M:%S")
#print (x, type(x))
#y=datetime.datetime.strptime(x,"%Y-%m-%d %H:%M:%S")
#print (y, type(y))
#print (z, type(z))
s_time=[]
for t in v_time:
    s_time.append(t.strftime("%Y-%m-%d %H:%M:%S").replace( ' ', 'T'))

print (s_time)

[cftime.DatetimeGregorian(2021, 12, 31, 0, 0, 0, 0, has_year_zero=False)
 cftime.DatetimeGregorian(2021, 12, 31, 3, 0, 0, 0, has_year_zero=False)
 cftime.DatetimeGregorian(2021, 12, 31, 6, 0, 0, 0, has_year_zero=False)
 cftime.DatetimeGregorian(2021, 12, 31, 9, 0, 0, 0, has_year_zero=False)
 cftime.DatetimeGregorian(2021, 12, 31, 12, 0, 0, 0, has_year_zero=False)
 cftime.DatetimeGregorian(2021, 12, 31, 15, 0, 0, 0, has_year_zero=False)
 cftime.DatetimeGregorian(2021, 12, 31, 18, 0, 0, 0, has_year_zero=False)
 cftime.DatetimeGregorian(2021, 12, 31, 21, 0, 0, 0, has_year_zero=False)]
['2021-12-31T00:00:00', '2021-12-31T03:00:00', '2021-12-31T06:00:00', '2021-12-31T09:00:00', '2021-12-31T12:00:00', '2021-12-31T15:00:00', '2021-12-31T18:00:00', '2021-12-31T21:00:00']


In [7]:
#lon=[-180, -90, 0, 90, 180]
#lat=[-90, 0, 90]
#m_lat,m_lon = np.meshgrid(lat,lon)
#print (m_lon.shape, m_lon)
#print (m_lat.shape, m_lat)

In [8]:
#print ('1', np.repeat([[1,2],[3,4]], 2))
#x = np.array( [[1,2],[3,4]] )
#print ('2a', np.repeat(x, 2))
#[     C C
#R    [1,2],
#R    [3,4]
#]
#print ('2b', np.repeat(x, 5, axis=1))
#print ('2c', np.repeat(x, 5, axis=0))
#print ('3', np.repeat(x, 3, axis=1))
#print ('4', np.repeat(x, [1, 2], axis=0))
#y=np.zeros((5, 2, 2))
#print (x.shape, y.shape)
#for i in range(5):
#    y[i]=x
#print (y[0])

vn_PHIS=np.zeros((72,361,576))
vn_PS=np.zeros((72,361,576))
vn_SLP=np.zeros((72,361,576))

for i in range(72):
    vn_PHIS[i]=v_PHIS[0]
    vn_PS[i]=v_PS[0]
    vn_SLP[i]=v_SLP[0]

print (vn_PS.shape)



(72, 361, 576)


In [9]:
charar = np.chararray(100, itemsize=19)
charar[:] = s_time[0]
#print (charar)
d = np.zeros(10, dtype='datetime64[s]')
#print (d)
d[:]=v_time[0]
print (d)

['2021-12-31T00:00:00' '2021-12-31T00:00:00' '2021-12-31T00:00:00'
 '2021-12-31T00:00:00' '2021-12-31T00:00:00' '2021-12-31T00:00:00'
 '2021-12-31T00:00:00' '2021-12-31T00:00:00' '2021-12-31T00:00:00'
 '2021-12-31T00:00:00']


In [10]:
#vf_CLOUD = v_CLOUD.flatten()
#vf_H     = v_H.flatten()
#print (v_SLP.shape)
#X, Y = np.meshgrid(x*geo_var.perspective_point_height, y*geo_var.perspective_point_height)
#vm_lon, vm_lat = np.meshgrid(v_lon, v_lat)
print (vn_PHIS.shape, v_PL.shape)


vm_time=np.zeros(14971392, dtype='datetime64[s]')

vm_lat, vm_lev, vm_lon = np.meshgrid(v_lat, v_lev, v_lon)


t_size=v_time.size

for t in range(t_size):
#    print (vn_SLP[t].shape)
#    print (t, v_time[t])
#    print (vm_lat.shape, vm_lon.shape)
#    print (vn_PS.shape, vn_PS[t].shape)
    
    vm_time[:] = v_time[t]
    print (vm_time.shape)
    x=np.dstack((
        vm_lon.flatten(), 
        vm_lat.flatten(), 
        vm_lev.flatten(),
        vm_time.astype('float'),
        v_CLOUD[t].flatten(), 
        v_DELP[t].flatten(),
        v_EPV[t].flatten(),
        v_H[t].flatten(),
        v_O3[t].flatten(),
        v_OMEGA[t].flatten(),
        vn_PHIS.flatten(), 
        v_PL[t].flatten(), 
        vn_PS.flatten(), 
        v_QI[t].flatten(), 
        v_QL[t].flatten(), 
        v_QV[t].flatten(), 
        v_RH[t].flatten(), 
        vn_SLP.flatten(), 
        v_T[t].flatten(), 
        v_U[t].flatten(), 
        v_V[t].flatten()
    ))
    fname = '/home/ec2-user/test' + s_time[t].replace(':', '_') + '.tsv.gz'
    np.savetxt(fname, x[0], fmt='%.5f', delimiter='~', newline="\n")


(72, 361, 576) (8, 72, 361, 576)
(14971392,)
(14971392,)
(14971392,)
(14971392,)
(14971392,)
(14971392,)
(14971392,)
(14971392,)


In [26]:
np.savetxt('test.tsv.gz', x[0], fmt='%.5f', delimiter='~', newline="\n")

In [37]:
print (x.shape)
for i in range(x.size):
    v_x=x[0][i]
    print (i, v_x)
    #np.savetxt('test.tsv', v_x, fmt='%.5f', delimeter='~', newline="\n")
    break
print (i, x.shape)
print (x[0][0].min())


(1, 14971392, 8)
0 [-1.80000000e+02 -9.00000000e+01  1.00000000e+00  2.75777090e+04
  6.86709297e+04  9.97232578e+04  0.00000000e+00  1.00000024e+00]
0 (1, 14971392, 8)
-180.0


In [16]:
#for l in range(v_lev.size):
#    print (l, v_lev[l])
    
lon=1
lat=140
level=1
print (v_T[0][level][lat][lon])

205.59442


In [6]:
v_time = nc.num2date(ds2['time'][:],ds2['time'].units, only_use_python_datetimes=True)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: WARNING: valid_range not used since it
cannot be safely cast to variable data type
  if __name__ == '__main__':
